Language:
  type: object
  required:
    - code
  properties:
    code:
      type: string
      maxLength: 2
    name:
      type: string
      maxLength: 50
    family:
      type: string
      maxLength: 100
Continent:
  type: object
  required:
    - name
  properties:
    name:
      type: string
      maxLength: 20
Country:
  type: object
  required:
    - code
  properties:
    code:
      type: string
      maxLength: 3
    code2:
      type: string
      maxLength: 2
    name:
      type: string
      maxLength: 60
    region:
      type: string
      maxLength: 60
    continent:
      type: Continent
    surface_area:
      type: number
    independance_year:
      type: integer
    population:
      type: integer
    life_expectancy:
      type: number
    gross_national_product:
      type: number
    government_form:
      type: string
      maxLength: 50
    head_of_state:
      type: string
      maxLength: 100
    languages:
        type: array
        items: CountryLanguage
City:
  type: object
  required:
    - id
  properties:
    id:
      type: integer
    name:
      type: string
      maxLength: 50
    country:
      type: Country
    region:
      type: string
      maxLength: 50
    population:
      type: integer
    longitude:
      type: number
    latitude:
      type: number
    altitude:
      type: number
    capital:
      type: boolean
CountryLanguage:
  type: object
  required:
    - country
    - language
  properties:
    country:
      type: Country
    language:
      type: Language
    official:
      type: boolean
    percentage:
      type: number

